name: CD Pipeline

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest

    - name: Run final tests
      run: |
        pytest

    - name: Build Docker image
      run: |
        docker build -t telegram-bot:${{ github.sha }} .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: |
        docker tag telegram-bot:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/telegram-bot:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/telegram-bot:latest

    - name: Deploy to server
      run: |
        echo "Deployment would happen here"
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
